---
# build.yml: Create your host and group var files from this
- hosts: localhost
  gather_facts: no
  roles:
    - build
  vars:
    ntp_server_list:
      - 192.168.0.12
    dns_server_list:
      - 192.168.0.12
    dns_domain: sdn40r7.lab
    hypervisor: "<packet-device-private-ip>"
    public_if: eth0
    servers: 
      - { hostname: ns1.sdn40r7.lab,
          description: "name, ntp and dhcp server" ,
          inventory: nserver ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          disk_GB: 20 ,
          image_qcow2: /tmp/centos7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.12 ,
          gateway: 192.168.0.2,
          ntpservers: local , 
          nameservers: [ 8.8.8.8 , 4.4.4.4 ] ,
          interfaces: [
          { name: eth0 ,
            bridge: weave,
            ip: 192.168.0.12 ,
            netmask: 255.255.255.0 },
          { name: eth1 ,
            bridge: wan,
            ip: 10.250.250.2 ,
            netmask: 255.255.255.0 },
          { name: eth2 ,
            bridge: inet,
            ip: 80.80.80.2 ,
            netmask: 255.255.255.0 }
          ]      
         }
      - { hostname: vsd1.sdn40r7.lab,
          description: "Nuage Stand-Alone VSD, management plane" ,
          inventory: vsd ,
          Is_NM_enabled: true ,
          memory: 16777216 ,
          vcpu_num: 8 ,
          image_qcow2: /tmp/vsd40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.20 ,
          gateway: 192.168.0.2,
          interfaces: [
          { name: eth0 ,
            bridge: weave,
            ip: 192.168.0.20 ,
            netmask: 255.255.255.0 }
          ]      
         }
      - { hostname: util.sdn40r7.lab,
          description: "Util server for Nuage VNS" ,
          inventory: util ,
          Is_NM_enabled: true ,
          No_cloud_init: true ,
          Guestfish: true ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/util40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.23 ,
          gateway: 192.168.0.2,
          interfaces: [
          { name: eth0 ,
            bridge: weave,
            ip: 192.168.0.23 ,
            netmask: 255.255.255.0 }
          ]      
         }
      - { hostname: stat.sdn40r7.lab,
          description: "Stat server based on ElasticSearch" ,
          inventory: stat ,
          Is_NM_enabled: true ,
          No_cloud_init: true ,
          Guestfish: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/stat40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.24 ,
          gateway: 192.168.0.2,
          interfaces: [
          { name: eth0 ,
            bridge: weave,
            ip: 192.168.0.24 ,
            netmask: 255.255.255.0 }
          ]      
         }
      - { hostname: head1.sdn40r7.lab,
          description: "NSG-v Head End at Datacenter" ,
          inventory: nsg ,
          No_cloud_init: true ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/nsg40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: weave}
          ]      
         }
      - { hostname: head2.sdn40r7.lab,
          description: "NSG-v Head End at Datacenter" ,
          inventory: nsg ,
          No_cloud_init: true ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/nsg40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: weave}
          ]      
         }
      - { hostname: nsg1.sdn40r7.lab,
          description: "NSG-v at Branch 1" ,
          inventory: nsg ,
          No_cloud_init: true ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/nsg40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: branch1}
          ]      
         }
      - { hostname: nsg2.sdn40r7.lab,
          description: "NSG-v at Branch 2" ,
          inventory: nsg ,
          No_cloud_init: true ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/nsg40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: branch2}
          ]      
         }
      - { hostname: cli1.sdn40r7.lab,
          description: "client at branch1" ,
          inventory: client ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/centos7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: eth0 ,
            bridge: branch1 }
          ]
         }
      - { hostname: cli2.sdn40r7.lab,
          description: "client at branch2" ,
          inventory: client ,
          memory: 2097152 ,
          vcpu_num: 2 ,
          image_qcow2: /tmp/centos7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          interfaces: [
          { name: eth0 ,
            bridge: branch2 }
          ]
         }
    vsc_controllers:
      - { hostname: vsc1.sdn40r7.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /tmp/vsc40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.21 ,
          vsd_fqdn: vsd1.sdn40r7.lab,
          system_ip: 1.1.1.2,
          xmpp_username: vsc01,
          gateway: 192.168.0.2,
          interfaces: [
          { name: bof ,
            bridge: weave },
          { name: control ,
            bridge: weave,
            ip: 192.168.0.21 ,
            prefix: 24 }
          ],
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.2" 
          ]
         }
      - { hostname: vsc2.sdn40r7.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /tmp/vsc40r7.qcow2 ,
          hypervisor: "<packet-device-private-ip>",
          ansible_host: 192.168.0.22 ,
          vsd_fqdn: vsd1.sdn40r7.lab,
          system_ip: 1.1.1.3 ,
          xmpp_username: vsc02,
          gateway: 192.168.0.2,
          interfaces: [
          { name: bof ,
            bridge: weave },
          { name: control ,
            bridge: weave,
            ip: 192.168.0.22 ,
            prefix: 24 }
          ] ,      
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.2" 
          ]
         }
    ssh_key:
    - "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
