---
# tasks file for dhcpd-install

- name: "Waiting until 5min for server to come back"
  local_action: wait_for port=22 host="{{ ansible_host }}" search_regex=OpenSSH delay=30 timeout=300
  remote_user: dev
  become: false

- name: install dhcp
  yum: name=dhcp state=present

- name: Copy dhcpd.conf file to nserver
  template: src=dhcpd.conf.j2 backup=no dest=/etc/dhcp/dhcpd.conf

- name: start and enable dhcpd
  service: name=dhcpd state=started enabled=yes
