---

- name: Uncomment line LIBVIRTD_ARGS="--listen" at {{ hypervisor }}
  lineinfile:
    dest: /etc/sysconfig/libvirtd
    regexp: 'LIBVIRTD_ARGS='
    line: 'LIBVIRTD_ARGS="--listen"'
  remote_user: root
  delegate_to: "{{ hypervisor }}"

- name: Uncomment line listen_tls = 0 at {{ hypervisor }}
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: 'listen_tls ='
    line: 'listen_tls = 0'
  remote_user: root
  delegate_to: "{{ hypervisor }}"

- name: Uncomment line listen_tcp = 1 at {{ hypervisor }}
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: 'listen_tcp ='
    line: 'listen_tcp = 0'
  remote_user: root
  delegate_to: "{{ hypervisor }}"

- name : restarting libvirtd
  service:
    name: libvirtd
    state: restarted
  remote_user: root
  delegate_to: "{{ hypervisor }}"

- name: Adding some guidelines at file summary
  local_action: 'lineinfile dest=/home/dev/.summary
                 regexp="Create libvirt user:" line="Create libvirt user: saslpasswd2 -a libvirt virtmgr (set password to webvirtmgr)"'
